### ISSUE TITLE
Is there a way to run sudo make install-cal without using sudo

### ISSUE THREAD

**Issue by rukh-debug** [tnagorra/nepalical#10]
Because, we are having issue over due to that.

https://aur.archlinux.org/packages/nepali-calendar-gtk-git#comment-957630

**Comment by tnagorra** [comment]
`make install-call` directly copies the build outputs to respective directories.

It is not a necessary step to build the application.

**Comment by rukh-debug** [comment]
Thanks, i'll update the PKGBUILD accordingly.
