### ISSUE TITLE
gtk-version problem 

### ISSUE THREAD

**Issue by codeezer** [tnagorra/nepalical#2]
![image](http://i.imgur.com/U5hZqLY.jpg)

**Comment by tnagorra** [comment]
You have gtk 3.10 but a version 3.12 is required.
Instead try to replace line

``` html
<requires lib="gtk+" version="3.12"/>
```

with

``` html
<requires lib="gtk+" version="3.10"/>
```

in the file nepalical.glade and install again.

**Comment by codeezer** [comment]
Its not working with that solution :) 
Maybe i need to force install gtk 3.12 instead.

**Comment by tnagorra** [comment]
I thought it worked for ankit.

**Comment by codeezer** [comment]
but not for me :P 
![image](http://i.imgur.com/ATYBKjY.jpg)

**Comment by tnagorra** [comment]
you compiled and installed it again right?
Then maybe you should install gtk 3.12 :D
