### ISSUE TITLE
Problem installing dependencies while installing nepalical

### ISSUE THREAD

**Issue by chapagain** [tnagorra/nepalical#3]
Had problem **installing dependencies** while installing **nepalical**
```bash
# Didn't work
sudo apt-get install libgtkmm-3.0-dev ttf-indic-fonts
```
Replaced with the following and it worked!
```bash
# Worked
sudo apt-get install gtkmm-3.0 fonts-indic
```

**Comment by tnagorra** [comment]
Could you specify the linux distribution and the version you are using?

**Comment by chapagain** [comment]
I am using 64 bit Ubuntu 16.04.

**Comment by tnagorra** [comment]
The packages were for an older version of Ubuntu.
Maybe the packages have changes in Ubuntu 16.01.
I don' t currently run Ubuntu. I will change the readme as soon as I confirm.
Thank you for your feedback.
