### ISSUE TITLE
position

### ISSUE THREAD

**Issue by diwasx** [tnagorra/nepalical#4]
i wanna place it slightly up, any suggestion?

**Comment by tnagorra** [comment]
@diwasx I have not worked on user defined placement. But you can modify the source code to change 
the padding and recompile the program.

File: nepalical/src/nepalical/WindowT.cpp
Line:  130

Replace
```
 move(screen->get_width()-width-padding, screen->get_height()-height-padding);
```

with
```
 move(screen->get_width()-width-XPADDING, screen->get_height()-height-YPADDING);
```

where XPADDING and YPADDING are constants.

**Comment by diwasx** [comment]
thankyou 👍 :)
